### ISSUE TITLE
welcome cog: on_member_remove exception (AttributeError: 'Object' object has no attribute 'icon')

### ISSUE THREAD

**Issue by XordK** [XordK/Derby-College-Bot#26]
Traceback (most recent call last):
  File "C:\Users\c.jones\Documents\EMA\Projects\Derby-College-Bot\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\c.jones\Documents\EMA\Projects\Derby-College-Bot\src\cogs\welcome.py", line 40, in on_member_remove
    embed = await self.get_remove_embed(member)
  File "C:\Users\c.jones\Documents\EMA\Projects\Derby-College-Bot\src\cogs\welcome.py", line 141, in get_remove_embed
    icon_url = self.bot.main_guild.icon.url
AttributeError: 'Object' object has no attribute 'icon'

**Comment by XordK** [comment]
Fixed in latest commit on jones-dev branch
